import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SmoothScrollWrapper from '@/src/lib/util/SmoothScroll'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <SmoothScrollWrapper>
        <body className='bg-[#1e1e21] justify-between'>
          <link rel='shortcut icon' type='image/x-icon' href='favicon.ico' />
          <main className='flex-grow'>{children}</main>
        </body>
      </SmoothScrollWrapper>
    </html>
  )
}
