import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import VerticalNav from "@/src/ui/components/navigation/VerticalNav/VerticalNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#ece7e1] justify-between">
        <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
        <main className="flex-grow">{children}</main>
        <div className="flex justify-end items-end font-mono">
          <VerticalNav />
        </div>
      </body>
    </html>
  );
}
